// Code generated by hertz generator.

package api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "github.com/manteia/zhulong/biz/model/zhulong/api"
)

// HealthCheck .
// @router /health [GET]
func HealthCheck(ctx context.Context, c *app.RequestContext) {
	resp := new(api.HealthCheckResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetServerInfo .
// @router /api/v1/info [GET]
func GetServerInfo(ctx context.Context, c *app.RequestContext) {
	resp := new(api.ServerInfoResponse)

	c.JSON(consts.StatusOK, resp)
}
