// Code generated by hertz generator.

package api

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "github.com/manteia/zhulong/biz/model/zhulong/api"
)

// UploadVideo .
// @router /api/v1/videos [POST]
func UploadVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.VideoUploadRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.VideoUploadResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetVideoList .
// @router /api/v1/videos [GET]
func GetVideoList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.VideoListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.VideoListResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetVideoDetail .
// @router /api/v1/videos/:video_id [GET]
func GetVideoDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.VideoDetailRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.VideoDetailResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetVideoPlayURL .
// @router /api/v1/videos/:video_id/play [GET]
func GetVideoPlayURL(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.VideoPlayURLRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.VideoPlayURLResponse)

	c.JSON(consts.StatusOK, resp)
}

// DeleteVideo .
// @router /api/v1/videos/:video_id [DELETE]
func DeleteVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.VideoDeleteRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.VideoDeleteResponse)

	c.JSON(consts.StatusOK, resp)
}
