// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _healthcheckMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getserverinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getvideolistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletevideoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _video_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getvideodetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getvideoplayurlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}
