server:
  host: "localhost"
  port: 8080

minio:
  endpoint: "${MINIO_HOST}:${MINIO_PORT}"
  access_key: "${MINIO_ACCESS_KEY}"
  secret_key: "${MINIO_SECRET_KEY}"
  bucket: "${MINIO_BUCKET}"
  use_ssl: false

jwt:
  secret: "${JWT_SECRET}"
  expire: "${JWT_EXPIRE}"

upload:
  max_size: "${UPLOAD_MAX_SIZE}"
  allowed_types: "${UPLOAD_ALLOWED_TYPES}"