# 开发环境配置
server:
  host: "localhost"
  port: 8080

minio:
  endpoint: "localhost:9000"
  access_key: "admin"
  secret_key: "admin123456"
  bucket: "zhulong-videos-dev"
  use_ssl: false

jwt:
  secret: "development-secret-key"
  expire: "7d"

upload:
  max_size: "10MB"
  allowed_types: "video/mp4,video/avi,video/webm"
