# MinIO对象存储配置
minio:
  # 服务器端点
  endpoint: "${MINIO_HOST}:${MINIO_PORT}"
  
  # 访问凭证
  access_key: "${MINIO_ACCESS_KEY}"
  secret_key: "${MINIO_SECRET_KEY}"
  
  # 存储桶配置
  bucket: "${MINIO_BUCKET}"
  
  # 连接选项
  use_ssl: false
  region: "us-east-1"
  
  # 上传配置
  upload:
    chunk_size: "5MB"
    max_retries: 3
    timeout: "30s"
  
  # 预签名URL配置
  presigned:
    expire_time: "24h"
    
# 视频存储策略
storage:
  # 文件路径模式: videos/{year}/{month}/{videoId}.{ext}
  path_pattern: "videos/{year}/{month}/{videoId}.{ext}"
  
  # 缩略图路径: thumbnails/{year}/{month}/{videoId}.jpg
  thumbnail_pattern: "thumbnails/{year}/{month}/{videoId}.jpg"
  
  # 支持的视频格式
  allowed_formats:
    - "mp4"
    - "avi" 
    - "webm"
    - "mov"
    - "mkv"
  
  # 文件大小限制
  max_file_size: "2GB"